

class PIC3DInputFile:
    def __init__(self, file_name, sim_name, num_particle_types):
        self.file_name = file_name
        self.sim_name = sim_name

        self.case = "none"
        self.B = [0, 0, 0]
        self.box_size = [1, 1, 1]
        self.cells_number = [100, 100, 100]
        self.periodic = [1, 1, 1]

        self.dt = 0
        self.cycles_number = 0

        self.particles = []
        for i in range(0, num_particle_types):
            self.particles.append(CalcParticle(0, 0, 0, 0, [0, 0, 0], [0, 0, 0], [0, 0, 0]))

    def text_title1(self, title, file=None):
        print(f"\n#  %%%%%%%%%%%%%%%%%%%    {title}    %%%%%%%%%%%%%%%%%%", file=file)

    def text_title2(self, title, file=None):
        print(f"", file=file)
        self.text_comment(title, file)

    def text_comment(self, comment, file=None):
        print(f"# {comment}", file=file)

    def text_sim_param(self, file=None):
        print("SaveDirName = data", file=file)
        print(f"# RestartDirName = data", file=file)

        self.text_title2("New flags:", file)
        print(f"Case\t\t\t\t= GEMjik\t\t\t# Select the case", file=file)
        print(f"PoissonCorrection\t= no       # Poisson correction", file=file)
        print(f"WriteMethod\t\t\t= pvtk", file=file)

        print(f"SimulationName\t\t= {self.sim_name}  # Simulation name for the output", file=file)
        self.text_title2("Path to the python script generated by ParaView", file)
        print(f"ParaviewScriptPath = ../inputfiles/storePersistenceDiagram.py", file=file)

        print(f"# delta = 1", file=file)

        self.text_title1("TIME STEP PARAMETERS", file)
        print(f"\tdt\t\t= {self.dt}\t\t\t# dt = time step", file=file)
        print(f"\tncycles\t= {self.cycles_number}\t\t\t# cycles", file=file)
        print(f"\tth = {1.0}\t\t\t\t\t# th = decentering parameter", file=file)
        print(f"\tc = {1.0}", file=file)

        self.text_title1("SMOOTH PARAMETER", file)
        print(f"Smooth = {0.9}\t\t\t\t# Smoothing value (5-points stencil)", file=file)

    def text_mag_field(self, file=None):
        self.text_title1("MAGNETIC FIELD PARAMETER", file)
        print(f"\tB0x = {self.B[0]}", file=file)
        print(f"\tB0y = {self.B[1]}", file=file)
        print(f"\tB0z = {self.B[2]}", file=file)

    def text_box_param(self, file=None):

        self.text_title1("BOX PARAMETERS", file)
        print(f"\tLx = {self.box_size[0]}\t# Lx = simulation box length - x direction", file=file)
        print(f"\tLy = {self.box_size[1]}\t# Ly = simulation box length - y direction", file=file)
        print(f"\tLz = {self.box_size[2]}\t# Lz = simulation box length - z direction\n", file=file)

        print(f"\tnxc = {self.cells_number[0]}\t# nxc = number of cells - x direction", file=file)
        print(f"\tnyc = {self.cells_number[1]}\t\t# nyc = number of cells - y direction", file=file)
        print(f"\tnzc = {self.cells_number[2]}\t\t# nzc = number of cells - z direction", file=file)

        self.text_title1("MPI TOPOLOGY", file)
        self.text_comment("number of MPI subdomains in each direction", file)
        print(f"\tXLEN = {32}", file=file)
        print(f"\tYLEN = {1}", file=file)
        print(f"\tZLEN = {1}", file=file)

        self.text_comment("topology of subdomains in each dimension (1=true, 0=false)", file)
        print(f"\tPERIODICX = {self.periodic[0]}", file=file)
        print(f"\tPERIODICY = {self.periodic[1]}", file=file)
        print(f"\tPERIODICZ = {self.periodic[2]}", file=file)

    def text_particle_row(self, name):
        tt = str(name) + " = "
        for i in range(0, len(self.particles)):
            if name == "uth":
                value = self.particles[i].thermal_vel[0]
            elif name == "vth":
                value = self.particles[i].thermal_vel[1]
            elif name == "wth":
                value = self.particles[i].thermal_vel[2]
            elif name == "v0":
                value = self.particles[i].drift_vel[0]
            elif name == "u0":
                value = self.particles[i].drift_vel[1]
            elif name == "w0":
                value = self.particles[i].drift_vel[2]
            elif name == "npcelx":
                value = self.particles[i].part_per_cell[0]
            elif name == "npcely":
                value = self.particles[i].part_per_cell[1]
            elif name == "npcelz":
                value = self.particles[i].part_per_cell[2]
            elif name == "rhoINIT":
                value = self.particles[i].rho_init
            elif name == "rhoINJECT":
                value = self.particles[i].rho_inj
            elif name == "qom":
                value = self.particles[i].qom
            else:
                value = 0

            tt += str(value) + " "

        return tt

        # if name == "uth":
        #     value = p.thermal_vel[0]
        #
        # values = " ".join(str(p.thermal_vel[0]) for p in self.particles)
        # return f"{name} = {values}"

    def text_particle_param(self, file=None):
        self.text_title1("PARTICLE PARAMETERS", file)
        self.text_comment("ns = number of species", file)
        self.text_comment("0 = electrons", file)
        self.text_comment("1 = protons", file)
        self.text_comment("...", file)

        print(f"\tns = {3}", file=file)

        self.text_title2("qom = charge to mass ratio for different species", file)
        print(f"\t{self.text_particle_row('qom')}", file=file)
        # print(f"\tqom = {self.particles[0].qom} {1.0} {-64.0} {1.0}", file=file)

        self.text_title2("Initial density (make sure that plasma is neutral)", file)
        print(f"\t{self.text_particle_row('rhoINIT')}", file=file)
        print(f"\t{self.text_particle_row('rhoINJECT')}", file=file)
        # print(f"\trhoINIT =   {0.99}  {1.0}   {0.01}    {0.0}", file=file)
        # print(f"\trhoINJECT = {0.0}   {0.0}   {0.0}     {0.0}", file=file)

        self.text_title2("TrackParticleID[species] = 1=true, 0=false --> Assign ID to particles ", file)
        print(f"\tTrackParticleID= {0} {0} {1} {1}", file=file)

        self.text_title2("uth = thermal velocity for different species - Direction X", file)
        print(f"\t{self.text_particle_row('uth')}", file=file)
        self.text_comment("vth = thermal velocity for different species - Direction Y", file)
        print(f"\t{self.text_particle_row('vth')}", file=file)
        self.text_comment("wth = thermal velocity for different species - Direction Z", file)
        print(f"\t{self.text_particle_row('wth')}", file=file)


        self.text_title2("u0 = drift velocity   - Direction X", file)
        print(f"\t{self.text_particle_row('u0')}", file=file)
        # print(f"\tu0 = {0.0}   {0.0}  {0.002}  {0.0}", file=file)
        self.text_comment("v0 = drift velocity   - Direction Y", file)
        print(f"\t{self.text_particle_row('v0')}", file=file)
        # print(f"\tv0 = {0.0}   {0.0}   {0.0}  {0.0}", file=file)
        self.text_comment("w0 = drift velocity   - Direction Z", file)
        print(f"\t{self.text_particle_row('w0')}", file=file)
        # print(f"\tw0 = {0.0}   {0.0}   {0.0}  {0.0}", file=file)

        self.text_title2("npcelx = number of particles per cell - Direction X", file)
        print(f"\t{self.text_particle_row('npcelx')}", file=file)
        # print(f"\tnpcelx = {50} {50} {30} {3}", file=file)
        self.text_comment("npcely = number of particles per cell - Direction Y", file)
        print(f"\t{self.text_particle_row('npcely')}", file=file)
        # print(f"\tnpcely = {1} {1} {1} {1}", file=file)
        self.text_comment("npcelz = number of particles per cell - Direction Z", file)
        print(f"\t{self.text_particle_row('npcelz')}", file=file)
        # print(f"\tnpcelz = {1} {1} {1} {1}", file=file)

    def text_boundary_conditions(self, file=None):
        self.text_title1("BOUNDARY CONDITIONS", file)
        self.text_title2("PHI Electrostatic Potential", file)
        self.text_comment("0,1 = Dirichilet boundary condition", file)
        self.text_comment("2   = Neumann boundary condition", file)


        print(f"\tbcPHIfaceXright = {1}", file=file)
        print(f"\tbcPHIfaceXleft  = {1}", file=file)
        print(f"\tbcPHIfaceYright = {1}", file=file)
        print(f"\tbcPHIfaceYleft  = {1}", file=file)
        print(f"\tbcPHIfaceZright = {1}", file=file)
        print(f"\tbcPHIfaceZleft  = {1}", file=file)

        self.text_title2("EM field boundary condition", file)
        self.text_comment("0 = perfect conductor", file)
        self.text_comment("1 = magnetic mirror", file)
        self.text_comment("2 = constant charge open BC", file)

        print(f"\tbcEMfaceXright = {2}", file=file)
        print(f"\tbcEMfaceXleft =  {2}", file=file)
        print(f"\tbcEMfaceYright = {2}", file=file)
        print(f"\tbcEMfaceYleft =  {2}", file=file)
        print(f"\tbcEMfaceZright = {2}", file=file)
        print(f"\tbcEMfaceZleft =  {2}", file=file)

        self.text_title2("Particles Boundary condition", file)
        self.text_comment("0 = exit", file)
        self.text_comment("1 = perfect mirror", file)
        self.text_comment("2 = riemission", file)
        self.text_comment("3 = open BC out", file)
        self.text_comment("4 = open BC in", file)
        self.text_comment("Caveat: if your processor topology is set to be periodic in a direction "
                          "automatically the boundary condition in that direction will be periodic", file)

        print(f"\tbcPfaceXright = {3}", file=file)
        print(f"\tbcPfaceXleft =  {2}", file=file)
        print(f"\tbcPfaceYright = {3}", file=file)
        print(f"\tbcPfaceYleft =  {3}", file=file)
        print(f"\tbcPfaceZright = {3}", file=file)
        print(f"\tbcPfaceZleft =  {3}", file=file)

    def get_file_text(self, file=None):
        str_line = "\n<--------------------------------------------------------------------------->\n"


        enter = """# Publications that use results from iPIC3D need to properly cite  
# 'S. Markidis, G. Lapenta, and Rizwan-uddin. "Multi-scale simulations of 
# plasma with iPIC3D." Mathematics and Computers in Simulation 80.7 (2010): 1509-1519.'
#
#        Copyright 2015 KTH Royal Institute of Technology
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at 
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License."""

        print("\tgenerated by python script", file=file)
        print(str_line, file=file)
        print(enter, file=file)
        print(str_line, file=file)
        self.text_sim_param(file)




        self.text_mag_field(file)
        self.text_box_param(file)
        self.text_particle_param(file)
        self.text_boundary_conditions(file)

        print(str_line, file=file)

        self.text_title2("print to video results", file)
        print("\tverbose = 1", file=file)

        self.text_title2("velocity of the injection from the wall", file)
        print("\tVinj= 0.0", file=file)

        self.text_title2("CG solver stopping criterium tolerance", file)
        print("\tCGtol = 1E-3", file=file)

        self.text_title2("GMRES solver stopping criterium tolerance", file)
        print("\tGMREStol = 1E-3", file=file)

        self.text_title2("mover predictor corrector iteration", file)
        print("\tNiterMover  = 3", file=file)

        self.text_title2("Output for field", file)
        print("\tFieldOutputCycle = 10", file=file)
        print("\tFieldOutputTag   = B+E", file=file)
        print("\tMomentsOutputTag = rho", file=file)

        self.text_title2("Output for particles if 0 it doesnt save particles data", file)
        print("\tParticlesOutputCycle = 5000", file=file)
        print("\tParticlesOutputTag = position+velocity", file=file)

        self.text_title2("restart cycle", file)
        print("\tRestartOutputCycle = 0", file=file)
        print("\tCallFinalize=1", file=file)

    def set_mag_field(self, Bx, By, Bz):
        self.B[0] = Bx
        self.B[1] = By
        self.B[2] = Bz

    def set_box_size(self, Lx, Ly, Lz):
        self.box_size[0] = Lx
        self.box_size[1] = Ly
        self.box_size[2] = Lz

    def set_num_cells(self, nxc, nyc, nzc):
        self.cells_number[0] = nxc
        self.cells_number[1] = nyc
        self.cells_number[2] = nzc

    def set_time_par(self, dt, ncycles):
        self.dt = dt
        self.cycles_number = ncycles


    def set_thermal_vel(self, particle, uth_x, uth_y, uth_z):
        self.particles[particle].set_thermal_vel(uth_x,uth_y,uth_z)

    def set_drift_vel(self, particle, uth_x, uth_y, uth_z):
        self.particles[particle].set_drift_vel(uth_x,uth_y,uth_z)

    def set_npcell_vel(self, particle, uth_x, uth_y, uth_z):
        self.particles[particle].set_part_per_cell(uth_x,uth_y,uth_z)

    def set_part_par(self, particle, qom, rho_inj, rho_init):
        self.particles[particle].rho_inj = rho_inj
        self.particles[particle].rho_init = rho_init
        self.particles[particle].qom = qom

    def get_file_name(self):
        return self.file_name


class CalcParticle():
    def __init__(self, qom, rho_init, rho_inj, track, uth: list, v0: list, cell: list):
        self.qom = qom
        self.rho_init = rho_init
        self.rho_inj = rho_inj
        self.track_id = track
        self.thermal_vel = uth
        self.drift_vel = v0
        self.part_per_cell = cell

    def set_thermal_vel(self, u, v, w):
        self.thermal_vel[0] = u
        self.thermal_vel[1] = v
        self.thermal_vel[2] = w

    def set_drift_vel(self, u, v, w):
        self.drift_vel[0] = u
        self.drift_vel[1] = v
        self.drift_vel[2] = w

    def set_part_per_cell(self, u, v, w):
        self.part_per_cell[0] = u
        self.part_per_cell[1] = v
        self.part_per_cell[2] = w


# f = PIC3DInputFile("inp1.inp", "test01")
#
# with open("myfile.inp", "w") as file:
#     # pass
#     # print_results(file)
#     f.get_file_text(file)

# with open("myfile.inp", "w") as file:
#     file.write(f.get_file_text())